### ISSUE TITLE
s_checksum issues

### ISSUE THREAD

**Issue by WenhaoYu** [jtpereyda/boofuzz#107]
Hello everyone,I find if i pass a my own defined algorithm function to s_checksum,it may cause a error. so i check the code,and do some changes as blow:
in checksum.py:
add algorithm argument's type judgement
if type(self._algorithm) is not str:
            self.checksum_lengths[self._algorithm.__name__] = self._length
and in _get_dummy_value function :
def _get_dummy_value(self):
        if type(self._algorithm) is str:
            return self.checksum_lengths[self._algorithm] * '\x00'
        else:
            return self.checksum_lengths[self._algorithm.__name__] * '\x00'
hope it would be helpful  or anyone have good idea?

**Comment by jtpereyda** [comment]
WenhaoYu,

You said you already tried to pass in your own function. Could you post the code you used to do this? It appears that this should have worked.

If you want to add an algorithm into the code (which would make sense if it something that a lot of others may want to use), you should modify `Checksum._checksum()` and `Checksum.checksum_lengths`.

**Comment by jtpereyda** [comment]
Closed due to inactivity from opener and ottimo's related fix in PR #149.
