### ISSUE TITLE
Use iter to simplify mutatable interface

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#114]
A lot of fluff in BasePrimitive could be removed if we just made mutatable things iterable.

The interface is functionally the same: You get only one mutation at a time.

The interface would now be:
* \_\_iter__ to yield mutations
* Default value: Probably a separate property. Yielding it as the first iterator value would result in duplicate test cases, or the fuzzing code would need to skip every first mutation.
* num_mutations: As is.

While we're modifying things, make all member variables private if possible.

**Comment by jtpereyda** [comment]
It would also be helpful to get metadata for each test case:
 - Which item is being fuzzed.
 - A "name" for the test case. E.g, "IPv4.Header.Source"

**Comment by SR4ven** [comment]
Was implemented in a similar way in #422
