### ISSUE TITLE
Provide Repeatable Random Seeds

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#115]
```
grep -rni --exclude-dir .git --exclude-dir .idea "random"
```
Randomness in tests reduces repeatability. Remove randomness, or else provide a means to record and repeat seed values.

Update 2021-02-24: Using a repeatable seed is probably easier and better.

**Comment by SR4ven** [comment]
We are already using a fixed seed for random number generation.

https://github.com/jtpereyda/boofuzz/blob/2f1ea5cd0e7cd1c6ee4c17468570dbbc02952504/boofuzz/primitives/random_data.py#L56
