### ISSUE TITLE
Add make test

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#116]
pytest-bdd has a Makefile on which you can run `make` and `make test` to run all the tests. This is very nice. It would be nice to have something similar for boofuzz.

1. Makes it easier for developers to "run all the tests."
2. As the tox documentation describes, it would act "as a frontend to Continuous Integration servers, greatly reducing boilerplate and merging CI and shell-based testing."

**Comment by SR4ven** [comment]
Isn't that what we have tox for?
All we do is run `tox` to run all tests, for developers as well as CI.

**Comment by jtpereyda** [comment]
Yep, this looks outdated.
