### ISSUE TITLE
Continue fuzzing even if the target is not responding

### ISSUE THREAD

**Issue by kuspilur** [jtpereyda/boofuzz#134]
I was having some problems, but after some testing I figured out that boofuzz performs only three fuzzing iterations of a primitive, when it is not receiving data from the target. 

However, I want to fuzz each and every field of my protocol, even if the request doesn't generate response, or at least to revert the last fuzzed primitive to its default and to continue with the next one.

Currently Boofuzz jumps over to the next request (or finishes the fuzzing of the request), when no response is received in three fuzz attempts of a primitive and because of this it never reaches the fields (primitives) that are further down the protocol.

I can manually disable fuzzing of primitives, thus forcing it to fuzz the fields I want, but it would have been much easier to just let it fuzz all fields overnight.

Also now it never reaches past the first three attempts and thus the primitive is not extensively fuzzed. For example some value which is past the first three attempts may generate response or even trigger crash, however currently it never reaches for it as Boofuzz quits after three attempts. 

Is this expected behaviour and how do I make it fuzz through all values of the primitives, when the target doesn't responds to the requests? 

I am fuzzing a binary protocol and my sample request looks like this:
```
s_initialize("request")
s_byte(0x03, name="version", fuzzable=True)
s_byte(0x00, name="reserved", fuzzable=True)
s_binary("0x0016", name="length")
s_word(0x1111, name="pdu_type",  endian=">", fuzzable=True)
s_dword(0x00000000, name="data",  endian=">", fuzzable=True)
```

**Comment by kuspilur** [comment]
check_data_received_each_request=False from sessions.py did the trick. 
Increasing crash_threshold is another helpful option.

**Comment by jtpereyda** [comment]
Sorry for the delay. Glad It worked out! Maybe colored output would make it
more obvious when boofuzz finds a crash...
