### ISSUE TITLE
Failed to import sulley on windows xp

### ISSUE THREAD

**Issue by naymikm** [jtpereyda/boofuzz#135]
Boofuzz, pydbg, and pydasm seemd to install fine but process monitor errors with no CancelIoEx

Microsoft Windows XP [Version 5.1.2600]
(C) Copyright 1985-2001 Microsoft Corp.

C:\Documents and Settings\marcus\Desktop\boofuzz-master\boofuzz-master>python pr
ocess_monitor.py
Traceback (most recent call last):
  File "process_monitor.py", line 11, in <module>
    from boofuzz import utils
  File "C:\Documents and Settings\marcus\Desktop\boofuzz-master\boofuzz-master\b
oofuzz\__init__.py", line 27, in <module>
    from .serial_connection import SerialConnection
  File "C:\Documents and Settings\marcus\Desktop\boofuzz-master\boofuzz-master\b
oofuzz\serial_connection.py", line 4, in <module>
    from . import serial_connection_low_level
  File "C:\Documents and Settings\marcus\Desktop\boofuzz-master\boofuzz-master\b
oofuzz\serial_connection_low_level.py", line 2, in <module>
    import serial
  File "C:\Python27\lib\site-packages\serial\__init__.py", line 27, in <module>
    from serial.serialwin32 import Serial
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 15, in <modul
e>
    from serial import win32
  File "C:\Python27\lib\site-packages\serial\win32.py", line 182, in <module>
    CancelIoEx = _stdcall_libraries['kernel32'].CancelIoEx
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CancelIoEx' not found

**Update**: I downloaded a Vista VM and it installed perfectly on that.

**Comment by jtpereyda** [comment]
Looks like the trace includes 'import serial', which is a Python standard
library, suggesting the problem might be more with the specific Python
installation than boofuzz in particular. Can't say I've tried it on XP
before. Have you been able to run successfully on other operating systems
with the same Python version?

**Comment by naymikm** [comment]
Yes, I mirrored the install on a vista machine and it worked like a charm. Some random google searches seemed to suggest that serial does not play well with xp. Maybe that is the issue.

**Comment by jtpereyda** [comment]
OK good to know. Sounds like you can use an older version of PySerial: http://pyserial.readthedocs.io/en/latest/pyserial.html#older-versions

If you were just trying to use a procmon (process monitor) on the Windows XP machine, that would be a different scenario, and probably something worth deliberately supporting.

**Comment by naymikm** [comment]
Awesome I went back to my xp box and indeed pyserial 2.7 works. Procmon no longer errors when I run it. Thanks!
