### ISSUE TITLE
some examples do not work

### ISSUE THREAD

**Issue by ettisan** [jtpereyda/boofuzz#140]
The examples in the repo do not work with boofuzz

**Comment by jtpereyda** [comment]
The only standing example I have now is at: https://github.com/jtpereyda/boofuzz-ftp

But if the examples in the repo aren't working, it might be better to just take them out rather than misleading people. Thank you for the issue report!

**Comment by jtpereyda** [comment]
(The examples in the repo are leftover from Sulley)

**Comment by jtpereyda** [comment]
I added a README explaining which examples are working... but if anyone wants to try and salvage those old examples, I wouldn't complain.

**Comment by jtpereyda** [comment]
People have complained even with the README; it might be worth just dropping broken code from the repo.

**Comment by starek4** [comment]
Fixed by https://github.com/jtpereyda/boofuzz/pull/384.
