### ISSUE TITLE
Make s_size fuzzable by default

### ISSUE THREAD

**Issue by ettisan** [jtpereyda/boofuzz#141]
I don't understand why s_size is not fuzzable by default. IMHO for a lot of binary protocols size fields are the one of the most interesting fuzzing fields.

I know this was sulley's behaviour. 

Are there any arguments against also fuzzing size fields by default?

**Comment by jtpereyda** [comment]
Good point. I agree with changing it, and sounds like there are no objections so far. : ) I'll label 'enahancement'.

I checked the Sulley source again and it seems like it was the same with Sulley: https://github.com/OpenRCE/sulley/blob/e72d34380cb96115b6fea556d9b827e245a65758/sulley/blocks.py#L697

**Comment by jtpereyda** [comment]
Yeah, seems like something you would usually want to fuzz....

**Comment by jtpereyda** [comment]
@ettisan Thank you for the suggestion!
