### ISSUE TITLE
Make s_bytes

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#144]
The only way to create a field of an odd number of bytes is to use s_bit_field. Create an s_bytes or something that lets you specify an arbitrary byte length.

Issue created based on this mailing list question: https://groups.google.com/d/msg/boofuzz/RfTg3biZOIY/aMK7U8rBAAAJ

**Comment by jtpereyda** [comment]
Issue #131 seems to be a similar request

**Comment by SR4ven** [comment]
Implemented in #302
