### ISSUE TITLE
about a complete document

### ISSUE THREAD

**Issue by b09780978** [jtpereyda/boofuzz#154]
I try to use this framework, but I can get a good example.Therefore I think that you can make a wiki document for us.

**Comment by jtpereyda** [comment]
Hi @b09780978. I've written a couple blog posts here
 - [A simple FTP fuzzer with boofuzz](https://medium.com/@jtpereyda/a-simple-ftp-fuzzer-with-boofuzz-d02ceaf8ce7):
 - [Using the boofuzz procmon](https://medium.com/@jtpereyda/using-the-boofuzz-procmon-a77a23b34d5c)

There is also an ftp example repository here: https://github.com/jtpereyda/boofuzz-ftp
