### ISSUE TITLE
Make Block Constructor More Intuitive

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#157]
## Problem
When creating blocks in boofuzz, it's difficult to tell which constructor argument is the name, value, etc.

For example, see this block from [boofuzz-ftp](https://github.com/jtpereyda/boofuzz-ftp/blob/master/ftp.py):
```python
    s_initialize("stor")
    s_string("STOR")
    s_delim(" ")
    s_string("AAAA")
    s_static("\r\n")
```

For `s_initialize`, "stor" is the name of the bock being initialized. For `s_string`, "STOR" is the default value.

## Solution
One option is to make the name always present, that way it will always come first and the value will come later.

Another option is to make things look more like the [construct](https://construct.readthedocs.io/en/latest/), e.g.:

```python
 ethernet = Struct("ethernet_header",
    Bytes("destination", 6),
    Bytes("source", 6),
    Enum(UBInt16("type"),
        IPv4=0x0800,
        ARP=0x0806,
        RARP=0x8035,
        X25=0x0805,
        IPX=0x8137,
        IPv6=0x86DD,
    ),
 )
```

So the name always comes first, and then the values. In the case of `Struct` (the analog to boofuzz's `s_initialize`), the value is another set of objects.

Votes and opinions welcome!

**Comment by SR4ven** [comment]
Was implemented in #422 and #486
