### ISSUE TITLE
Possibility to compute custom checksum over the block

### ISSUE THREAD

**Issue by i-am-providence** [jtpereyda/boofuzz#158]
It may be useful to able to compute checksum using user-provided algorithm implementation, eg pass a routine to the checksum block constructor

**Comment by jtpereyda** [comment]
I believe this is possible by passing a function to the Checksum `algorithm` parameter and the expected length of the checksum to `length`. Is this what you're looking for?

**Comment by i-am-providence** [comment]
Hmm, looks so, probably I'm missing something, I'll try and report back soon. Sorry

**Comment by i-am-providence** [comment]
You was totally right, I should have better RTFM. This snippet with dumb user-provided checksum works like charm:
``` python
from boofuzz import *


def sample_checksum(data):
    return data * 2

def main():
    """
    Hands-on example on L2 protocol fuzz.
    """
    session = Session(
                target=Target(
		        connection=SocketConnection(
                                host='eth1',
                                timeout=1.0,
                                proto='raw-l2')))
    s_initialize("TEST")
    s_binary("00190F291C48") # DST
    s_binary("0000100A0B0C") # SRC
    s_binary("0800") # ethertype
    s_random(1, min_length=1, max_length=1, name="forchecksum")
    s_checksum("forchecksum", algorithm=sample_checksum, length=4)

    session.connect(s_get("TEST"))
    session.fuzz()


if __name__ == "__main__":
    main()
```

**Comment by jtpereyda** [comment]
@i-am-providence I'll work on some more helpful docstrings for the Checksum object. Can we use that excerpt as an example in the dosctrings?

**Comment by i-am-providence** [comment]
@jtpereyda sure you can
