### ISSUE TITLE
GUI - Keep UI persistent after test complete

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#166]
Right now boofuzz quits as soon as it is done, which frees up the command line, but closes the HTTP interface, which is frustrating if you wanted to actually see the results.

Some options:
1. Spin off a process that lets you browse results after the test is complete. As a security consideration, would need to verify server only listens on localhost.
2. Have the command line app stay alive with a "Press any key to quit" or similar.

**Comment by starek4** [comment]
I think that this is already implemented.

**Comment by SR4ven** [comment]
Second option was implemented by #260
