### ISSUE TITLE
Add Logger Example to Quickstart Guide

### ISSUE THREAD

**Issue by GQYYY** [jtpereyda/boofuzz#171]
I am trying to use this framework to fuzz HTTP, but I cannot have a good example about the API usage, especially the "Logging" Module. How to efficiently use the logging APIs to check the fuzzing  procedure? I wish you could write a complete documentation, including example and tutorial. Thank you!

**Comment by jtpereyda** [comment]
There is API documentation, though perhaps not as many examples as one would like: http://boofuzz.readthedocs.io/en/latest/#api-documentation

Different loggers are here: http://boofuzz.readthedocs.io/en/latest/user/logging.html

As for how to use, see the `fuzz_data_logger` parameter for `Session` here: http://boofuzz.readthedocs.io/en/latest/source/Session.html

It would probably be best to add a note about logging to the Quickstart guide. Also, the Session object API docs make it seem like you need to pass a `FuzzLogger` but I _think_ you can pass any `IFuzzLogger`.

**Comment by dzervas** [comment]
Can I pass multiple loggers?
I want both console logging and file logging (csv?)
I also want all the results, not only the crashes (I'm testing an embedded system over UART, so its crashes can't be detected)

**Comment by jtpereyda** [comment]
@dzervas You can do this via the [FuzzLogger object](http://boofuzz.readthedocs.io/en/latest/user/logging.html#fuzzlogger-object) which takes a list of IFuzzLoggers in its constructor.

All data is logged by default.
