### ISSUE TITLE
can not run with jupyter

### ISSUE THREAD

**Issue by ysnrgtslash** [jtpereyda/boofuzz#179]
since boofuzz require tornado==4.0.2. jupyter can not run with the version. 
i would like to change the requirement

**Comment by jtpereyda** [comment]
Sounds like a good plan; I don't think it really needs to be 4.0.2. Would you be willing to test it out with a more updated version and open a pull request?

You can try just `tornado` and take out the version altogether.

**Comment by yasunorigoto** [comment]
even removed version 4.20  from setup.py, boofuzz looks fine for now.  let me use it for a while. 
thanks.
