### ISSUE TITLE
Upgrade Algorithm to Fuzz Multiple Fields at the Same Time

### ISSUE THREAD

**Issue by cq674350529** [jtpereyda/boofuzz#187]
Hi, does `boofuzz` or `sulley` support mutate multi fields at the same time?

    s_byte(12, name='magic_1')
    s_string('hello', name='key')
    s_byte(34, name='magic_2')
    s_string('world', name='value')

Take the above code as a simple example, how to mutate fields `magic_1`，`magic_2`，`value` simultaneously ? Because a payload may cause crash like `34hello78aaaaaaaaaaaaaaaaaaaaa`?

In my opinion, the strategy `boofuzz` or `sulley` takes now is to mutate each field one by one.  Do I misunderstand?

Thanks in advance!

**Comment by jtpereyda** [comment]
You are correct. This would be a great feature to have. Obviously the combinatorial possibilites explode a lot more quickly in this scenario, so there are some tricks to making it work.

**Comment by SR4ven** [comment]
Implemented in #499
