### ISSUE TITLE
Retry indefinitely on connection issues instead of failing immediately

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#193]
A lot of communication errors result in a failed test case currently. It makes more sense to engage in some retry behavior, with a possible long term timeout. It is meaningless to push forward with a test if connection errors are still in place.

Add some kind of retry behavior (possibly in the Target class?). Depending on some setting:
 1. Retry indefinitely or
 2. Retry for n retries or x amount of time or
 3. Don't retry at all

**Comment by jtpereyda** [comment]
Might as well retry indefinitely for most vulnerability research use cases. Failing could be useful in some scenarios like signaling test failure to an automated system.

**Comment by dorpvom** [comment]
I tried addressing this in #363
