### ISSUE TITLE
Switch ports when multiple instances running

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#194]
boofuzz will choke when running two instances because it tries to reuse the web port. Instead:
1. Add logic to search and grab an unused port
2. Allow the URL to be printed for the user's convenience

To do so:
1. Separate the server startup from the fuzz start.

**Comment by starek4** [comment]
I believe this is already implemented and we can close it.

**Comment by SR4ven** [comment]
> 1. Add logic to search and grab an unused port
> 2. Allow the URL to be printed for the user's convenience

Are done.

I'm not sure about
> Separate the server startup from the fuzz start.

but we already have [Session.server_init()](https://boofuzz.readthedocs.io/en/stable/source/Session.html#boofuzz.Session.server_init)

@jtpereyda are all tasks completed?

**Comment by jtpereyda** [comment]
Good catch, thanks @starek4 @SR4ven
