### ISSUE TITLE
process_monitor_unix.py -c default parameter

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#195]
Add a default value for the -c / --crash_bin parameter to process_monitor_unix.py. Just choose a reasonable file name.

**Comment by starek4** [comment]
Seems that this is already implemented. The filename is the same as in windows process monitor, so it is consistent too.

https://github.com/jtpereyda/boofuzz/blob/577dd499d31100250846f30aa0eadac723f2a0f3/process_monitor_unix.py#L61-L68

**Comment by SR4ven** [comment]
It indeed seems like the default value was already implemented in 0974a7737cd3458e7fcd003123138b07cafacb99.

@starek4 have you tested this and can verify that it works as intended?

**Comment by starek4** [comment]
Yes, working as intended.
![image](https://user-images.githubusercontent.com/2153835/74339760-01997c00-4da5-11ea-90e6-46aa88dad884.png)

**Comment by SR4ven** [comment]
Thanks for checking @starek4
