### ISSUE TITLE
boofuzz.s_size() is not calculating the size correctly for boofuzz.s_dword

### ISSUE THREAD

**Issue by hduarte** [jtpereyda/boofuzz#197]
When boofuzz.s_size() is used with the default math function, the size of a boofuzz.s_dword() is not being correctly calculated. For example if one calculates the size of a block with only an s_dword() inside the block and with a value of 1 digit, the reported size is 4. Changing the length of sizer doesn't change this.

What am I missing @jtpereyda ?

Thks for your help.

**Comment by jtpereyda** [comment]
@hduarte at least for binary format, 4 bytes is the correct size. byte = 1 byte. word = 2 bytes. dword = 4 bytes. qword = 8 bytes.

**Comment by jtpereyda** [comment]
@hduarte I confirmed that the length is calculated incorrectly in format 'ascii'

**Comment by hduarte** [comment]
@jtpereyda yes that's the issue. I have submitted a pull request with the patch that calculates the correct length when the format is ascii https://github.com/jtpereyda/boofuzz/pull/198

**Comment by jtpereyda** [comment]
@hduarte very good find.
