### ISSUE TITLE
Question, Is there a way to send a valid test case?

### ISSUE THREAD

**Issue by TheUserThe** [jtpereyda/boofuzz#199]
When I used sully in the past I couldn't find an easy way to test my protocol specification. I had to add an additional block and skip to it. Is there a better way?

**Comment by jtpereyda** [comment]
@TheUserThe Great question, this feature has long been missing.

This feature is experimental and can be previewed on the `webui` branch. The `Session` class has a new `feature_check` method. You can call this method just like `fuzz`, but it will run the tests with no mutations. It will print out a message for each message path taken.

Any feedback on this feature would be appreciated! Especially while it is still pre-release.

Warning: This branch has a lot of improvements, including some that break backward compatibility (usually in small ways or with obscure features). Not all such changes have been documented yet.

**Comment by TheUserThe** [comment]
@jtpereyda Thanks. I will give it try and keep you posted.

**Comment by jtpereyda** [comment]
Closing as `feature_check` is now in master branch.
