### ISSUE TITLE
Web UI issue in the latest update

### ISSUE THREAD

**Issue by cq674350529** [jtpereyda/boofuzz#206]
Hi, in the latest version of `boofuzz`, there is an issue about the Web UI. The `reason` is obtained through a `for` loop and placed in the `<div>` tag. 
https://github.com/jtpereyda/boofuzz/blob/8fd172079585ed05ab454c1d620d819009fa3967/boofuzz/web/templates/index.html#L48-L54
The actual view is as follows.
![snipaste20180809_142911](https://user-images.githubusercontent.com/13868458/43882111-169d30a0-9be1-11e8-9817-c7aec11bb7a8.png)
Maybe just place the `{{crash.reasons}}` in the `<td>` tag.
![snipaste20180809_143556](https://user-images.githubusercontent.com/13868458/43882250-9d555b68-9be1-11e8-9819-fe0718e4e45f.png)

By the way, there is an change in the method `transmit_fuzz()`, a new field `self._receive_data_after_fuzz` is used. But another method `transmit_normal()` keeps the same.  So what's the difference between the two methods? I have read the method docstring, but still get confused. 

Thanks in advance! Also, congratulations to you on your great work (`boofuzz`) presented on the BH Arsenal.

**Comment by cq674350529** [comment]
I am sorry. Today I have tested it again, the Web UI works well in the latest update. I am not sure why it behaves strangely yesterday. So I'll close the issue. Sorry again.

**Comment by jtpereyda** [comment]
@cq674350529 thank you for the update. On some browsers you may need to do a hard refresh after updating boofuzz in order to clear the browser cache. On Chrome you can hold `Ctrl` while clicking the Refresh button.

**Comment by jtpereyda** [comment]
The reasoning behind `transmit_normal()` and `transmit_fuzz()` differing is that, for many protocols, it is reasonable to do a receive after every transmitted message. However, after a fuzzed message, many implementations will not respond to the invalid message. If you do a receive after fuzzing against a server like this, you may have to wait until the connection times out, which will increase the time each test case takes to execute.

**Comment by cq674350529** [comment]
Got it. Thanks!
