### ISSUE TITLE
Is there an easy way to keep multi fields in sync?

### ISSUE THREAD

**Issue by cq674350529** [jtpereyda/boofuzz#226]
Hi, sometimes when fuzzing xml, I need to keep two fields in sync.  Take the following xml as an example:

    <key>aaaa</key>

The possible value of xml tag may be [`key1`, `key2`]. Thus, I choose the `s_group()` like this:

    s_group('group_start', values=TEST_TAGS)
    with s_block('tmp'):
        s_static('>')
        s_static('aaaa')
        s_static('</')
    s_group('group_end', values=TEST_TAGS)

It will procedure 3 combinations (`<key1>aaaa</key1>`, `<key2>aaaa</key1>`, `<key1>aaaa</key2>`). But what I want are `<key1>aaaa</key1>` and `<key2>aaaa</key2>`.
> above example taken is kept as simple as possible

So is there an easy way to accomplish this?  Although I can do this with `edge.callback()` or `session.pre_send()`.

Any advice would be appreciated! Thanks in advance.

**Comment by jtpereyda** [comment]
@cq674350529 I don't believe there's any element that does exactly this. This would be a cool feature to have. It would be doable and could be based off of `s_checksum`.

**Comment by jtpereyda** [comment]
Thanks for s_mirror @cq674350529 !
