### ISSUE TITLE
Custom target restart method

### ISSUE THREAD

**Issue by SR4ven** [jtpereyda/boofuzz#239]
I was looking for a way to add a custom restart method for a target but could only find the EventHook class, which doesn't seem to be fully implemented yet. Is there a way to make use of it somehow?
More precisely I ways looking for a way to simply ping the target with an ICMP-Request to see when it is back up. If you are interessted in having this feature in the project, I could try to get that to work too.
Thinking about it, two different aproaches come to my mind:

1. Check if importing scapy is possible and simply use one of it's ping functions (ARP/ICMP/TCP/UDP).
2. Implenting it from scrap, building an ICMP-Request packet, sending it and waiting for a response.

Either way the targets IP would be required and would have to be entered and passed to the Session class somehow. Maybe reuse l2_dst from the SocketConnection class?

**Comment by jtpereyda** [comment]
@SR4ven It would be great to have a generic way to add a custom restart method. Some brainstorming on the details:

The most generic facility would be one or both of:
1. Execute an external command to do restart.
2. Call a custom restart method written in Python.

The integration points could be:
1. Add a mechanism to register restart methods with the `Session` class. (See the `register_post_test_case_callback` and `_post_send` methods for an example*)
2. Add a mechanism to the procmon system. This would essentially be a `restart_commands` option akin to `start_commands`

The procmon integration is a natural fit with the external command, and the Session integration is a natural fit with the custom Python method.

* The `_post_send` method is a bit cluttered. And honestly it might make more sense to pass a restart method (or list of restart methods) into the constructor rather than making a special `register..` method that simply appends an item to a list.

**Comment by jtpereyda** [comment]
As for how to implement a ping method in Python, you can Google around for `Python ping.py` to see some options out there. There is at least one ping package that uses raw sockets (I haven't tested it personally), and my Python install also comes with a ping.py script that uses impacket.

**Comment by SR4ven** [comment]
Executing an external command would be really nice but I've done some tests with `subprocess` and I've noticed a very anoying problem described [here](https://stackoverflow.com/questions/1367373/python-subprocess-popen-oserror-errno-12-cannot-allocate-memory). Calling `subprocess.popen()` is requesting once more as much memory as Python is already eating up.
This is very bad when running a big fuzzing session that can use multiple Gb of RAM as calling popen() will crash with `OSError: [Errno 12] Cannot allocate memory`.
I don't know if Python 3 handles that in another way but with Python 2 I don't think `subprocess` is an option and I don't know of any other save methods to execute commands.

I got how `register_post_test_case_callback` and could probably make something like this work for a restart mechanism. What I didn't quite get is how an approach to passing methods into the constructor would look like.
Also, wouldn't the procmon system only work for local targets running a local process?

**Comment by jtpereyda** [comment]
Yeah, starting another Python process is suboptimal. The only advantage is flexibility -- you could call other non-Python processes too. 

> Also, wouldn't the procmon system only work for local targets running a local process?

Depends on how exactly your ping situation works, but yes -- the procmon approach only works if the code can run where the procmon is running. The Session approach only works if the code can run where the rest of boofuzz is running.

I like the Session approach best, I think.

> how an approach to passing methods into the constructor would look like.

Here's an example of the register method:
```python
def http_check(target, fuzz_data_logger, session, sock, *args, **kwargs):
    ###########################################################################
    # Failure detection code goes here
    #
    ###########################################################################
    target.open()
    target.send(REQUESTS['get-request'].original_value)
    response = target.recv()
    fuzz_data_logger.log_check('Verifying response contains "200 OK"')
    if '200 OK' in response:
        fuzz_data_logger.log_pass()
    else:
        fuzz_data_logger.log_fail('Response did not contain 200 OK')

...
def main():
    ...
    session.register_post_test_case_callback(http_check)
```

So you could pass a method into the constructor using a similar approach:
```python
    session = Session(
        target=Target(
            connection=SocketConnection(target_host, target_port, proto='tcp'),
        ),
        sleep_time=0,
        post_test_case_callback=httpcheck
    )
```

**Comment by SR4ven** [comment]
Ok thanks for the clarification.
To me it would make sense to adapt the `post_test_case_callback` as well, but that would result in a breaking change. Should the `register_post_test_case_callback()` function stay in redundantly or shall I just leave the post_test_callback as it is for now?

**Comment by SR4ven** [comment]
Completed with #248
