### ISSUE TITLE
Handle missing test cases in UI

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#242]
With the new DB optimization, a fuzz record database can have missing cases. UI should be updated to match.

Quote from PR #233:
When trying to access a non existent test case in the Web UI there is a constant flow of errors like here:
```
File "/home/papgft/.local/lib/python2.7/site-packages/boofuzz/fuzz_logger_db.py", line 146, in get_test_case_data
    test_case_row = next(c.execute('''SELECT * FROM cases WHERE number=?''', [index]))
StopIteration
ERROR:tornado.access:500 GET /api/test-case/17 (127.0.0.1) 1.01ms
```
That only happens when using `boo open` to view the log. We might want to take a look at that here or in a new issue/request.

_Originally posted by @SR4ven in https://github.com/jtpereyda/boofuzz/pull/233#issuecomment-465108708_

**Comment by SR4ven** [comment]
Fixed in #268
