### ISSUE TITLE
Add Docs Build to CI

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#243]
Avoid issues like #240

**Comment by SR4ven** [comment]
PR #245 should have fixed that but the docs status is still on failing. Are they only rebuilt on a release or a manual trigger maybe?

**Comment by jtpereyda** [comment]
@SR4ven You can see the builds here: https://readthedocs.org/projects/boofuzz/builds/ Looks like it has been trying to build

**Comment by SR4ven** [comment]
That helps finding the problem!
The build fails because of a ldap3 version mismatch. No idea where that comes from though.

**Comment by SR4ven** [comment]
@jtpereyda Completed with #245 and #249
