### ISSUE TITLE
Failed to replace '\x' with '' in s_binary()

### ISSUE THREAD

**Issue by cq674350529** [jtpereyda/boofuzz#294]
`ValueError: invalid literal for int() with base 16: '\x12\x11'` occurred in `s_binary()` when running the following code.

    s_initialize('test_s_binary')
    s_binary("\x12\x11")
    session.connect(s_get('test_s_binary'))
    session.fuzz()

In `s_binary()`, `parsed = parsed.replace("\\x", "")` will fail against `\x12\x11`. In the following `while` loop,  it will get each 2 bytes and translate it with `int(pair, 16)` ,thus causing `int('\x12\x11', 16)`.

At the moment, I didn't find an elegant way to deal with both `'0x1a0x1b'` and `'\x1a\x1b'`.

https://github.com/jtpereyda/boofuzz/blob/d1324f61162397749216a06b642805606117f181/boofuzz/__init__.py#L392-L399

By the way, there is also a py2/py3 compatibility issue against `value`. Maybe using `value=b""` instead.

**Comment by aedrax** [comment]
good call about the value not being set as binary, I made the fix there and another location and created a pull request

**Comment by jtpereyda** [comment]
@aedrax which PR is that?

**Comment by aedrax** [comment]
it had made it in the feature/python3 PR where I was doing the binary compatibility updates. Note: that doesn't resolve this issue. Just the value being a binary type in @cq674350529's last sentence.

**Comment by jtpereyda** [comment]
@cq674350529 your example would work with the string `"\\x12\\x11"`. The string `"\x12\x11"` does not contain any backslashes. Rather, it contains exactly two characters, one defined by the hex value `12` and the other by the hex value `11`. `s_binary` is not meant to receive raw binary data, but is rather meant to receive a string of characters representing raw binary data in hex format.

**Comment by jtpereyda** [comment]
Closing as this looks like a usage error. Feel free to comment for further discussion.
