### ISSUE TITLE
ImportError: No module named shutil_get_terminal_size

### ISSUE THREAD

**Issue by icecolor-wiattack** [jtpereyda/boofuzz#308]
I have this problem after updating the latest boofuzz.
But I did have the ‘backports.shutil’ library installed.
But still can't run. Many people have the same problem

**Comment by SR4ven** [comment]
@icecolor-wiattack did you install boofuzz from pip or the current source?
If you are using v0.1.5 from pip, #293 is not included which might fix your problem.

Please [install](https://boofuzz.readthedocs.io/en/latest/user/install.html) boofuzz from the current source and check again.

**Comment by jtpereyda** [comment]
@icecolor-wiattack Thank you for reporting this issue. Sounds like we need to cut another release to get the latest code into PyPI.

**Comment by SR4ven** [comment]
Should be fixed in #293, closing.
