### ISSUE TITLE
Random token with each new request

### ISSUE THREAD

**Issue by DanNegrea** [jtpereyda/boofuzz#310]
Hi,

I need to send a random (new) value for a token with each request. 
How can this be implemented? This field does not need to be fuzzed.

I tried  without success a few variants with  s_random. One example is bellow:

```python
#!/usr/bin/env python
from boofuzz import *

session = Session(
    target=Target(
        connection=SocketConnection("127.0.0.1", 8000, proto='tcp')))

s_initialize("get")
s_static("GET /")
s_string("index.html", size=-1, padding='-', encoding='ascii', fuzzable=True, max_len=2, name=None)
s_static(" HTTP/1.1\r\n")
s_static("Connection: close\r\n")
s_static("Token: ")
s_random("0", 0, 2, num_mutations=25, fuzzable=False, step=None, name=None)
s_static("\r\n\r\n")

session.connect(s_get("get"))
session.fuzz()
```

**Comment by SR4ven** [comment]
@DanNegrea you need to use callbacks for that. Boofuzz will iterate through the blocks of the request sequentially, so while one bock is mutated, all other blocks stay with their default value.

One way would be to define a static token and change it with [this callback](https://boofuzz.readthedocs.io/en/latest/source/Session.html#boofuzz.Session.connect) after each request.
#306 deals with a similar case.

**Comment by DanNegrea** [comment]
@SR4ven thanks for the tip.

I found a solution:

```python
#!/usr/bin/env python
from boofuzz import *

token = 0

def increment_token(target, fuzz_data_logger, node, session, edge, *args, **kwargs):
    global token
    node.names['token']._value = str(token)
    token += 1
    return node.render()

session = Session(
    target=Target(connection=SocketConnection("127.0.0.1", 8000, proto='tcp')))

s_initialize("get")
s_static("GET /")
s_string("index.html", size=-1, padding='-', encoding='ascii', fuzzable=True, max_len=2, name=None)
s_static(" HTTP/1.1\r\n")
s_static("Connection: close\r\n")
s_static("Token: ")
s_random(0, 0, 2, fuzzable=False, name="token")
s_static("\r\n\r\n")

session.connect(s_get("get"), callback=increment_token)
session.fuzz()
```

Still, this makes me raise some questions:

- what is fuzzable used for? Just as a switch if someone decides to not fuzz all fields?
- would it be easier to include one static descriptor that does exactly what I need? That are many protocols that require a unique something
- "pre_send_callbacks" on target sounds promising for implementing this, but lacks the "node" parameter. What is the purpose of this callback?

These questions are extra. I consider the issue closed.

**Comment by SR4ven** [comment]
Good to hear that you found a solution.
- You are right about the fuzzable option
- So far the callback method worked fine and it's got the pro of being very flexible, a new block/primitive might be easier in some cases, but wouldn't be that universal. If you want, feel free to implement a new block and open a PR.
- the pre_send_callbacks are for when you need to generate checksums, open a statefull connection, etc.

**Comment by cq674350529** [comment]
Here is a picture from the `Sulley` framework. It may be helpful to understand the callbacks better.

![session_graph](https://user-images.githubusercontent.com/13868458/62017299-b47b0180-b1e8-11e9-91ac-e20971232e36.png)
