### ISSUE TITLE
Network & Process monitoring - practical examples

### ISSUE THREAD

**Issue by pedroflor** [jtpereyda/boofuzz#315]
Hi everybody...
can anyone please write some examples (using vulnserver.exe) showing how to monitor the availability of the server/service by network and by process?

The deployment could be:
boofuzz (Linux) => vulnserver.exe (Windows)

Thanks and best regards.

**Comment by Marshall-Hallenbeck** [comment]
I just started using Boofuzz and found this resource which might be exactly what you're looking for: https://zeroaptitude.com/zerodetail/fuzzing-with-boofuzz/

**Comment by pedroflor** [comment]
Thanks!

**Comment by Sunxingzhezhexingsun** [comment]
> I just started using Boofuzz and found this resource which might be exactly what you're looking for: https://zeroaptitude.com/zerodetail/fuzzing-with-boofuzz/

Is this link still available? I can't access it.

**Comment by Marshall-Hallenbeck** [comment]
@Sunxingzhezhexingsun 

http://web.archive.org/web/20210128050740/https://zeroaptitude.com/zerodetail/fuzzing-with-boofuzz/
