### ISSUE TITLE
Process monitor - start_commands options for server arguments

### ISSUE THREAD

**Issue by thuanpv** [jtpereyda/boofuzz#320]
Hi All,

I have successfully set up BooFuzz to fuzz some servers which have simple starting commands like this LightFTP server https://github.com/hfiref0x/LightFTP. To start the server, I just need to run "fftp" so I set up the start_commands option of the BooFuzz process monitor easily as follows

`procmon_options['start_commands'] = ['path to fftp']
`

However, I am working with another server which takes some arguments and I still cannot set it up. I have tried two ways

`procmon_options['start_commands'] = ['path to server', 'list of arguments']
`

and

`procmon_options['start_commands'] = ['path-to-server list-of-arguments']
`

but none of them works. I normally receive the following error from Process Monitor
"No such file or directory while starting list-of-arguments" or "No such file or directory while starting path-to-server list-of-arguments".

I have read the Sulley document at http://www.fuzzing.org/wp-content/SulleyManual.pdf but I could not find a solution.

Has anyone faced and solved a similar issue?

Your help would be really appreciated!

Thanks

**Comment by thuanpv** [comment]
I have resolved this issue. I read the code and see BooFuzz/Sulley use Popen to start the target server so I update start_commands as follows and it works now

`procmon_options['start_commands'] = [['path-to-server', 'arg1', 'arg2']]
`

**Comment by jtpereyda** [comment]
@thuanpv glad you found an answer; happy fuzzing!

**Comment by behnamben** [comment]
@thuanpv Do you have the code for fuzzing LightFTP available?
