### ISSUE TITLE
s_int(): 'value' parameter  dose not support list type

### ISSUE THREAD

**Issue by JsHuang** [jtpereyda/boofuzz#330]
In sulley , an int primitive could be defined as follows:
```
s_int(
    value=[1,2,3],
    format='binary',
    signed=False,
    full_range=False,
    fuzzable=True,
    name='int_value',
)
```
thus the `int_value` will only mutated from the value list [1,2,3].
Hower, this definition in boofuzz will get error while fuzzing:
```
Traceback (most recent call last):
  File "s_int_test.py", line 24, in <module>
    session.fuzz()
  File "C:\Python27\lib\site-packages\boofuzz\sessions.py", line 598, in fuzz
    self._main_fuzz_loop(self._iterate_protocol())
  File "C:\Python27\lib\site-packages\boofuzz\sessions.py", line 703, in _main_fuzz_loop
    self._fuzz_current_case(*fuzz_args)
  File "C:\Python27\lib\site-packages\boofuzz\sessions.py", line 1406, in _fuzz_current_case
    repr(self.fuzz_node.mutant.original_value),
  File "C:\Python27\lib\site-packages\boofuzz\primitives\base_primitive.py", line 26, in original_value
    return self._render(self._original_value)
  File "C:\Python27\lib\site-packages\boofuzz\primitives\bit_field.py", line 127, in _render
    temp = self.render_int(value, output_format=self.format, bit_width=self.width, endian=self.endian, signed=self.signed)
  File "C:\Python27\lib\site-packages\boofuzz\primitives\bit_field.py", line 151, in render_int
    bit_stream += int_to_binary_string(value, bit_width)
  File "C:\Python27\lib\site-packages\boofuzz\primitives\bit_field.py", line 36, in int_to_binary_string
    return "".join(map(lambda x: str((number >> x) & 1), range(bit_width - 1, -1, -1)))
  File "C:\Python27\lib\site-packages\boofuzz\primitives\bit_field.py", line 36, in <lambda>
    return "".join(map(lambda x: str((number >> x) & 1), range(bit_width - 1, -1, -1)))
TypeError: unsupported operand type(s) for >>: 'list' and 'int'
```

How to solve it?

**Comment by SR4ven** [comment]
You could try the `s_groups` primitive. [Docs](https://boofuzz.readthedocs.io/en/latest/user/static-protocol-definition.html#boofuzz.s_group)

HTTP GET request example:
https://github.com/jtpereyda/boofuzz/blob/944cab821074cadc42cb86ac9ede19a8006e9f32/requests/http_get.py#L15-L63

**Comment by JsHuang** [comment]
Thanks！

**Comment by JsHuang** [comment]
OK , s_group can accept list assignment , but s_group has no `fuzzable` attribute, how can I give a primitive more than 1 default value and  can still fuzz it ?

**Comment by SR4ven** [comment]
When you call `sess.fuzz()` it will not iterate through the default values of a block, whether it is a single one or a list.
I don't know of a built-in option to extend the fuzz_library of a single block but a quick workaround for your problem could be
```python
s_int(value=1, name='int_value')
...
sess.connect(s_get("Test"))
sess.nodes[1].names['int_value']._fuzz_library.append(42)
sess.fuzz()
```
You need to select the correct node for your use case (I used a debugger to check).

**Comment by JsHuang** [comment]
Thanks , that works for me.

**Comment by SR4ven** [comment]
Good to hear that your problem is fixed.

Closing again, feel free to reopen if you have any more questions.

**Comment by jtpereyda** [comment]
Related feature request: https://github.com/jtpereyda/boofuzz/issues/212
