### ISSUE TITLE
s_size() is not working in POST Request sample

### ISSUE THREAD

**Issue by jungmingg** [jtpereyda/boofuzz#331]
It looks like s_size() is not working in POST Request sample
I want to send POST Request but if it has include **output_format="ascii"** is not working on HTTP
If i remove **output_format=ascii**, i can check HTTP(POST) packet through wireshark(default binary)
Please let me know if I did something wrong

Below is the sample code you provided :

`# Basic fuzz of post payloads

s_initialize("HTTP VERBS POST")
s_static("POST / HTTP/1.1\r\n")
s_static("Content-Type: ")
s_string("application/x-www-form-urlencoded")
s_static("\r\n")
s_static("Content-Length: ")
s_size("post blob", **output_format="ascii"**, signed=True, fuzzable=True)
s_static("\r\n")
if s_block_start("post blob"):
    s_string("A" * 100 + "=" + "B" * 100)
s_block_end()
s_static("\r\n\r\n")`

**Comment by starek4** [comment]
Hi @jungmingg ,

I use `s_size()` quite often and it works for me just fine. I have two questions.

1] Why do you use `signed=True`? The default value is `False`. I am quite sure, that you cannot have negative size HTTP body :) So, keep it as default.

2] Do you need to fuzz this field? You set the parameter `fuzzable` to True, which means that this value is fuzzed. So Boofuzz will generate some request with fuzzed content-length value. It depends on what you want to fuzz, but if you are fuzing some HTTP data, I am quite sure that you do not want to fuzz this field.

So, maybe you want to edit the line like this:
`s_size("post blob", output_format="ascii", fuzzable=False)`

I am using Boofuzz like this and it works like a charm.

**Comment by starek4** [comment]
Well, I thing `s_size` works as expected. I add an example of using it for HTTP fuzzing to examples folder in #384. If @jungmingg says otherwise, I suggest closing this issue.
