### ISSUE TITLE
Block problem!

### ISSUE THREAD

**Issue by TongweiRen** [jtpereyda/boofuzz#332]
I'm trying to build a MQTT packet sent to broker by publisher. Here is some of my code:
s_initialize("Packet")
with s_block("Packet"):
        s_static("\x32", name='Header')
        s_size("Payload", fuzzable=False)
        if s_block_start("Payload"):
            s_size("Topic", fuzzable=False)
            if s_block_start("Topic"):
                s_string("perf/test")
                s_delim("")
            s_block_end()
            s_static("\x00\x03")
            s_delim("")
            s_string("1234567890")
        s_block_end()
session.connect(s_get("Packet"))

When I run the test case, the real packet is this
![Screen Shot 2019-10-04 at 1 36 25 PM](https://user-images.githubusercontent.com/51735297/66227832-01c59480-e6ac-11e9-9ae3-934b621ef967.png)

I don't know why the topic length is 0, and topic and message is none!

**Comment by TongweiRen** [comment]
PS: the picture is about a fuzz packet, so message identifier is different with the code, but it won’t influence the results.

**Comment by starek4** [comment]
Well, I hear about MQTT first time and maybe my answer will be completely wrong, but it seems to me that packet length field can be from 1 to 4 bytes, depending on the actual payload packet size ([source](http://www.steves-internet-guide.com/mqtt-protocol-messages-overview/)). In Boofuzz, the default length of `s_size` is 4 bytes. So you should set the length parameter of `s_size` primitive according to how long your messages will be (you can define max. length of other primitives too). It is just the first thing I have noticed, so maybe I am missing something but hopes that it will help.

**Comment by starek4** [comment]
Basically, this is the difference which I want to describe in the previous comment

### 1) `s_size` with a length of 4 (default)
```python
from boofuzz import *

s_initialize("Packet")
with s_block("Packet"):
    s_size("Payload", fuzzable=False, length=4)
    if s_block_start("Payload"):
        s_static("\x07")
        s_block_end()

print(s_render())
```

Output:
`b'\x01\x00\x00\x00\x07'`

### 2) `s_size` with a length of 1
```python
from boofuzz import *

s_initialize("Packet")
with s_block("Packet"):
    s_size("Payload", fuzzable=False, length=1)
    if s_block_start("Payload"):
        s_static("\x07")
        s_block_end()

print(s_render())
```

Output:
`b'\x01\x07'`

As your message is shorter than 127 bytes (just that one you posted here, Boofuzz can generate bigger one!), you need just 1 byte for the length. So, you can try to set `s_size` length just to 1 byte.

**Comment by starek4** [comment]
Well, and according to the [posted source](http://www.steves-internet-guide.com/mqtt-protocol-messages-overview/), there is a **Remaining Length** field, which complicates things even more. For longer messages, s_size cannot be used 😞
