### ISSUE TITLE
cannot send http protocol properly

### ISSUE THREAD

**Issue by chinguunhr** [jtpereyda/boofuzz#356]
Hi, Folks

I am just trying to fuzz Kolibri v2 web server. But wireshark cannot decode some traffic. I don't understand why boofuzz sending payload including "/.:/" 
For example - "GET /.:/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

![2](https://user-images.githubusercontent.com/45087107/69961253-73a04a00-1546-11ea-94bc-202ed0e2022a.png)
![1](https://user-images.githubusercontent.com/45087107/69961265-7a2ec180-1546-11ea-889a-eeac4e02cdb3.png)

**Comment by cq674350529** [comment]
Hi, how do you define the requests to be fuzzed? The payload sent by `boofuzz` depends on how you define it.

**Comment by chinguunhr** [comment]
Hi,
I used below script.
from boofuzz import *


def main():
    session = Session(
        target=Target(
            connection=SocketConnection("192.168.0.101", 8081, proto='tcp',)
        ),sleep_time=3
    )

    s_initialize(name="Request")
    with s_block("Request-Line"):
        s_group("Method", ["GET"])
        s_delim(" ", name='space-1', fuzzable = False)
        s_string("/index.htm", name='Request-URI', fuzzable = True)
        s_delim(" ", name='space-2', fuzzable = False)
        s_string("HTTP/1.1", name='HTTP-Version', fuzzable = False)
        s_delim("\r\n", name='return-1', fuzzable = False)
        s_string("Host:", name="Host", fuzzable = False)
        s_delim(" ", name="space-3", fuzzable = False)
        s_string("192.168.0.101:8081", name="Host-Value", fuzzable = False)
        s_delim("\r\n", name="return-2", fuzzable = False)
        s_string("Connection:", name="Connection", fuzzable = False)
        s_delim(" ", name="space-4", fuzzable = False)

        s_string("keep-alive", name="Connection-Value", fuzzable = False)
        s_delim("\r\n", name="return-3", fuzzable = False)
        s_string("DNT:", name="DNT", fuzzable = False)
        s_delim(" ", name="space-5", fuzzable = False)
        s_string("1", name="DNT-Value", fuzzable = False)
        s_delim("\r\n", name="return-4", fuzzable = False)
        s_string("Upgrade-Insecure-Requests:", name="Upgrade-Insecure-Requests", fuzzable = False)
        s_delim(" ", name="space-6", fuzzable = False)
        s_string("1", name="Upgrade-Insecure-Requests-Value", fuzzable = False)
        s_delim("\r\n", name="return-5", fuzzable = False)
        s_string("User-Agent:", name="User-Agent", fuzzable = False)
        s_delim(" ", name="space-7", fuzzable = False)
        s_string("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", name="User-Agent-Value", fuzzable = False)
        s_delim("\r\n", name="return-6", fuzzable = False)
        s_string("Accept:", name="Accept", fuzzable = False)
        s_delim(" ", name="space-8", fuzzable = False)
        s_string("text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3", name="Accept-Value", fuzzable = False)
        s_delim("\r\n", name="return-7", fuzzable = False)
        s_string("Accept-Encoding:", name="Accept-Encoding", fuzzable = False)
        s_delim(" ", name="space-9", fuzzable = False)
        s_string("gzip, deflate", name="Accept-Encoding-Value", fuzzable = False)
        s_delim("\r\n", name="return-8", fuzzable = False)
        s_string("Accept-Language:", name="Accept-Language", fuzzable = False)
        s_delim(" ", name="space-10", fuzzable = False)
        s_string("en-US,en;q=0.9,mn-MN;q=0.8,mn;q=0.7", name="Accept-Language-Value", fuzzable = False)
        s_delim("\r\n", name="return-9", fuzzable = False)
        s_static("\r\n", name="Request-Line-CRLF")
    s_static("\r\n", "Request-CRLF")

    session.connect(s_get("Request"))

    session.fuzz()

**Comment by cq674350529** [comment]
As shown in the following, there is an inbuilt fuzz_library containing this item.
https://github.com/jtpereyda/boofuzz/blob/544e795de4a8c86836e62649885dc06126e46138/boofuzz/primitives/string.py#L63-L67

Maybe the quickest way to resolve this is to comment out those containing `'\x00'`, which "break" the HTTP protocol.

**Comment by chinguunhr** [comment]
Hnnn, Got it.

Thanks for your help.
