### ISSUE TITLE
Documentation Template

### ISSUE THREAD

**Issue by mistressofjellyfish** [jtpereyda/boofuzz#375]
Hey,

so I know this was discussed recently in #347, but I have a few more comments on the situation. In particular, I have one major issue with the current theme - the menu sidebar is completely gone if my browser only occupates 1/2 of my 1920x1080 screen.

![Unbenannt](https://user-images.githubusercontent.com/7026857/73277412-6cb25280-41ea-11ea-84f3-a5ad9300d457.PNG)

To access the menu, I have to scroll all the way down. In my opinon, this sucks from an UX perspective. How easy is it for us to modify the theme? If we could reasonably easy modify the template, I'd propose an [off-canvas approach](https://www.w3schools.com/howto/howto_js_off-canvas.asp). If not, I would advocate for discussing another theme again.

**Comment by SR4ven** [comment]
Did this problem arise with #347? We only upped the width to increase readability, which shouldn't be connected to the sidebar behaviour.

The sidebar hiding is rooted [here](https://github.com/bitprophet/alabaster/blob/3b68afcfe55a80508254b22904294100a160e6a7/alabaster/static/alabaster.css_t#L613). We could overwrite this as described in the [docs](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html#overriding-or-replacing-a-theme-s-stylesheet).
I wouldn't recommend simply deactivating this feature, as it can be helpful on small screens. The off-canvas approach sounds like a good solution for this, but someone would have to implement and maintain this feature.
An existing theme with such a feature or similar behaviour would be preferable, but we couldn't find one as #347 showed. However, I'm always open for suggestions.

**Comment by mistressofjellyfish** [comment]
Nope, it's also present in the stable version, as it's a "misfeature" of alabasta. Maybe it'd be a good idea to directly open an issue about this in the alabasta repository? Surely boofuzz isn't the only user of the theme; and the UX issue is obvious. Skimming through their issues, I couldn't find a prior discussion on this issue, so maybe it's worth a shot.

As far as I can tell, the easiest way to implement this would be to fork alabasta and implement proper off-canvas rendering there. But then again, I'd be tempted to fix more issues regarding narrow screen width and legibility and accessibility. In no particular order:

- Without a visible sidebar, the template desperately needs at least breadcrumbs at the top; preferably the project name as a Link to the docs index as well
- Ditching Georgia in favor for Roboto (body), Roboto serif (headings), Roboto mono (code) which are all *way* more legible on my screen
- implementing a better way to highlight code xrefs (currently they have a background color that almost blends with the white background on my screen)
- Use a semi-bold font for the th tags in descriptions to avoid bluring with the actual definitions in these lists

And honestly, I could go on, that's only what I gathered after looking 5 minutes into the theme. There is a reason so many people use the RTD theme; from a designer's standpoint it's simply far better than alabasta.

**Comment by SR4ven** [comment]
Not exactly related to your issue, but I played around with a custom CSS for the RTD theme and think we could make that one look pretty sleek too.

![grafik](https://user-images.githubusercontent.com/46794237/73286909-ad18cd00-41f8-11ea-8bb8-3e02a01eb878.png)

The RTD theme also has the off-canvas sidebar for small screens so that's really nice. On top I noticed that the page scales much better at different screen sizes than Alabaster.

![grafik](https://user-images.githubusercontent.com/46794237/73287759-07fef400-41fa-11ea-86a1-508d1d5405d4.png)

RTD theme with some custom colouring has my vote :D

**Comment by mistressofjellyfish** [comment]
Yeah, LGTM. After a bit more thinking, I came to the conclusion that once the issues I have with alabasta are fixed it would be quite similar to the RTD theme anyways.

That being said, there are a few things that need to be adressed for good legibility; in no particular order:

- Contrast issues
    - Black on dark gray at sidebar's top
    - Blue on dark gray at sidebar's headings
    - Source Code may be fine, but that needs to be tested
    - gray version number on dark gray background
    - https://webaim.org/resources/contrastchecker/ This is a nice contrast checker I use when I do web stuff. Aim for a minimum of 4,5:1 for anything that's essential.

Do you have your branch pushed somewhere I could look into? I'll happily provide my stance on the theme.

**Comment by SR4ven** [comment]
Thanks for the feedback @mistressofjellyfish.
I did all the editing directly in the browser as it was meant to be no more but a preview of what's possible. So no, I don't have this on a pushed branch.

Things that need to be done:
- Test if we can use a custom css that overwrites some of the RTD theme values as described [here](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html#overriding-or-replacing-a-theme-s-stylesheet)
- Agree on a colour scheme
- Get a logo if possible
- Implement the customised theme

I doubt that I'll have the time to implement these changes in the next time, so feel free to open a PR if you like. I'm always happy to review.

**Comment by SR4ven** [comment]
Unexpectedly, I found some time to work on this, so I implemented the requirements for a custom theme.
https://github.com/jtpereyda/boofuzz/tree/custom_css
https://boofuzz.readthedocs.io/en/custom_css/

We now have to agree on a colour scheme and adjust the css in docs/_static/css/custom.css
Personally, I prefer white and dark grey backgrounds with some contrasting bright colour font.

PRs on this branch are very welcome.

**Comment by jtpereyda** [comment]
@SR4ven LGTM; curious what @mistressofjellyfish thinks.

Guess I'm in the minority not liking RTD. I like using a couple color tweaks to break up the standard look.

**Comment by mistressofjellyfish** [comment]
Well, RTD scales nicer, but that's not really a surprise, is it?

I think the gray colorscheme suggested by @SR4ven looks nice, but I'm fine with mostly anything that is nicely readable and allows me to read the docs on a half width screen, so I guess its fine.

Honestly though there are not many ways to have the general layout of the docs done, and apart from color tweaks more breaks down to simple usability questions than to questions of taste IMHO. If someone goes forward and proposes a set of colors, I'd happily look into that and provide feedback,

**Comment by SR4ven** [comment]
I pushed some more changes to the CSS. Would be nice if someone could take a look and share thoughts/suggestions.

Though we don't necessarily need a logo, it would greatly improve the looks of the docs. I still don't know where to get one from (for free). Any ideas?

If we decide to go without a logo I'll open a PR in the next step.

**Comment by mistressofjellyfish** [comment]
> Any ideas?

I happen to have some graphics skill. If you can wait until about mid-march, I might be able to get a few things proposed - depending on your taste. Maybe I can sketch something up with the nice costume boo has in monsters inc, that has these antenna eyes that could be the oo in boofuzz - or something like that.

**Comment by SR4ven** [comment]
That would be super awesome @mistressofjellyfish! There's no need to hurry, we can add the logo later at any time.
I really like your idea about the costume of boo. Looking forward to seeing the sketch!
In case that gets too complex, something more generic would do it too.

**Comment by jtpereyda** [comment]
Thanks for the work on this @SR4ven and @mistressofjellyfish . Looking forward to that logo :)
