### ISSUE TITLE
static node may be fuzzed once?

### ISSUE THREAD

**Issue by cq674350529** [jtpereyda/boofuzz#376]
During a simple test, I found that if a node has no mutable field, it won't be tested. Take a simple case  as an example:

```python
s_initialize("static_node")
s_static("static")

session.connect(s_get("static_node"))
```

After `session.fuzz()` called, no data was sent actually. This single node wasn't "fuzzed".

Is it expected? In my opinion, the node should be "fuzzed" once to generate one test case. Thanks!

> I didn't come across such cases in reality though.

**Comment by SR4ven** [comment]
I'd say this is the expected behaviour. In my protocol definitions the default values of the primitives usually hold data which is needed for an intact packet.

When a primitive is being fuzzed, it's default value is ignored. I mean it wouldn't be fuzzing if we send only valid data right?
As far as I know you can use the [transmit_normal](https://boofuzz.readthedocs.io/en/stable/source/Session.html#boofuzz.Session.transmit_normal) method to transmit intact packets.

**Comment by cq674350529** [comment]
Thanks. 
Further, I did additional simple tests.

```python
s_initialize("first")
s_string("1", max_len=1)
s_static("first end")

s_initialize("second")
s_static("second end")

s_initialize("third")
s_string("3", max_len=1)
s_static("third end")
```

If only connected the first two nodes, the `second` node was ignored. That is, no data containing "second end" was sent.

```python
session.connect(s_get("first"))
session.connect(s_get("first"), s_get("second"))
    
session.fuzz()
```

If connected all the nodes, the `second` node was traversed. That is, some data containing "second end" were sent.

```python
session.connect(s_get("first"))
session.connect(s_get("first"), s_get("second"))
session.connect(s_get("second"), s_get("third"))
    
session.fuzz()
```

So if this is the expected behavior, it's ok. Of course, as to the first case, other mechanisms such as `post_send()` may be used to accomplish it.

After all, I haven't come accross such cases in reality, maybe later.

**Comment by jtpereyda** [comment]
That makes sense, in fact I'm surprised it works out to be that tidy -- the second node is sent only if needed as a prerequisite for something that is being fuzzed.

There is no "all-valid" test case. The current "normal" use case would see the second message in your example being sent as part of the `Session.feature_check()` method, which you should generally use while configuring your fuzzer and target.

**Comment by cq674350529** [comment]
Thanks. Just curious for this behaviour. I'll try the `Session.feature_check()` later.
