### ISSUE TITLE
Binary Install for Windows Not Applicable

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#39]
The latest wheel doesn't have Windows binaries.

This might not be worth maintaining, in which case the quick fix is to remove the binary subsection from INSTALL.rst.

**Comment by jtpereyda** [comment]
Consider adding pip install instructions (once PR #38 is fixed).

**Comment by aedrax** [comment]
I believe this is working again, just tested on my windows machine
