### ISSUE TITLE
boofuzz Logo

### ISSUE THREAD

**Issue by mistressofjellyfish** [jtpereyda/boofuzz#407]
Hey,

as promised in #375 I have a sketch for a boofuzz logo. At the moment It's nothing more than a quick sketch which I'll refine later when I have time. Consider all art I post CC0. Obviously, I have vectors (SVG/EPS) for each sketch as well, but they probably need some cleanup before I can post them. If you have more Ideas or if you picture something, feel free to comment.

![boo-logo](https://user-images.githubusercontent.com/7026857/77890484-d34a0000-726f-11ea-9fb5-3ed60e261aff.png)
![boo-logo-color](https://user-images.githubusercontent.com/7026857/77891556-69325a80-7271-11ea-9cde-3081bfa47f06.png)

Font currently used is Source Sans Pro, although that may change. I tried to include more of boos halloween costume, but unfortunately that would mess up the proportions of the logo too much, especially if it should be recognizable even when displayed small.

Personally, I like the color one better; but ultimately, that's up to you @jtpereyda.

**Comment by jtpereyda** [comment]
Genius! I like the blue one too. That is perfect. My wife is beside herself. XD

Let's put it on the RTD site, and maybe the README too?

**Comment by SR4ven** [comment]
Great job @mistressofjellyfish! I really like it!

I too fancy the colored version. How about coloring the eyes purpleish just like the costume of Boo? Just an idea that came to my mind, no clue if actually looks good.

I also just remembered that we still need a favicon for the webinterface. I could imagine just the eyes in 256x256px looking good there too.
If it's not too much work that'd be a really nice addition.

**Comment by mistressofjellyfish** [comment]
> How about coloring the eyes purpleish just like the costume of Boo?

According to [this image](https://de.cleanpng.com/png-fkq3l7/preview.html), the eyes aren't that purple but more of a metallic blue. I played with the eyeball color a bit, but ultimately even slight off-white hints make a huge optical difference when paired against the white background of e.g. github. None the less I made a purple version; I think I didn't really get the color quite right but it's close enough I guess.

> I also just remembered that we still need a favicon for the webinterface.

Vectors don't really have pixels, but what I have is 150x150mm which equals 460x460px when rendered to PNG at 300dpi. In any case, favicons should be in .ico format as that's the only thing actually supported anyway. Unfortunately, Affinity Designer doesn't let me export that directly; so I'll probably have to convert it with Photoshop or whatever.

Purple eyes:
![boo-logo-purple](https://user-images.githubusercontent.com/7026857/77997203-46667b80-732f-11ea-8485-a225277fe724.png)

Favicon:
![favicon](https://user-images.githubusercontent.com/7026857/77997209-4b2b2f80-732f-11ea-8b31-30bd981a5ea7.png)

**Comment by SR4ven** [comment]
So I rendered the docs with the logo and favicon and I think we've got some contrast issues there.
Against the grey background the black font of the logo only has a contrast ratio of 1,6:1 (the background is #303030 btw if you want to check other colors).
It's either changing the docs theme or adjust the logo. Maybe a dark mode version of the logo is an option?
![Screenshot_2020-03-31 boofuzz Network Protocol Fuzzing for Humans — boofuzz 0 1 6 documentation](https://user-images.githubusercontent.com/46794237/78041227-b9dcad00-7370-11ea-807a-4cb480c5b687.png)
![Screenshot_2020-03-31 Installing boofuzz — boofuzz 0 1 6 documentation](https://user-images.githubusercontent.com/46794237/78041237-bba67080-7370-11ea-914e-8c5e5f8bb498.png)
Don't mind the pixelated pictures, that's just the compression of the screenshots and it's not visible on the webpage.

I found a somewhat helpful guide about favicons [here](https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/). Though some browsers might not support it, I'm a fan of SVG favicons. No more worries about correct sizes and pixelated images. Most browsers support them nowdays, see [this](https://caniuse.com/#feat=link-icon-svg) (66% of all users).
The network monitor of Firefox revealed that Github also provides an SVG favicon, the only difference here is, that they are able to provide fallbacks which we can't.
In case we decide against SVG, a 32x32px ICO will do it too.

**Comment by mistressofjellyfish** [comment]
> Maybe a dark mode version of the logo is an option?

Of course. What I'll usually do is make a stencil version of the logo, bascially all outlines in a uniform white color for use on black backgrounds; and the same in a black version. This enables anyone to place the logo on virtually any background, even if it's not a bright neutral one. I'll provide a render tomorrow; I guess I'll open a PR and include all vector files as well.

That being said, SVG Favicons aren't a serious option unless the last two Chromium versions have support for them. IE users are not the target audience here, but Chrome 79 doesn't have support and still about 20% market share. The general rule I try to follow in webdev is "use it if support is > 90% user base or a polyfill is available". Unfortunately, for svg favicons I don't know of any.

**Comment by jtpereyda** [comment]
The purple idea occurred to me. I couldn't find a frame online from the movie that showed the eye colors clearly. Now that I see the purple though I'm not sure if I like that or the blue better.

**Comment by SR4ven** [comment]
I too kinda like the purple one more, even if it doesn't represent the real color. Looks really nice on dark backgrounds too.
Looking forward to seeing the other versions you mentioned @mistressofjellyfish.
