### ISSUE TITLE
Print Errors Gracefully when in Curses mode

### ISSUE THREAD

**Issue by jtpereyda** [jtpereyda/boofuzz#421]
Currently, unhandled exceptions are printed out in the Curses mode in a messy way, and when you exit the error disappears.

Proposed fix:

1. When an unhandled exception occurs, gracefully kill Curses mode and print the trace to normal STDOUT

This would be especially helpful when developing a fuzzer. As is, I always turn off Curses mode until my fuzzer is stable enough. Otherwise, whenever I hit an error, I need to manually disable Curses mode, run the test again, and hope I still see the error.

Related: #418

**Comment by SR4ven** [comment]
I understand the problem you're describing, but I can't reproduce it or think of a possible case.
Whenever I get uncaught errors, they appear on the curses screen in a more or less readable way, the test stops and you can quit the GUI by pressing `q`. After that I still get the traceback printed to the console as usual.

I recently found an issue with quitting the GUI that resulted in a broken console window. I have a fix for it at https://github.com/SR4ven/boofuzz/tree/curses_fixes, so you could see if that fixes your problem or provide some code to reproduce the behaviour you get?

**Comment by jtpereyda** [comment]
Here's a reproducing example, tested on master commit `e496b97` just now.
```
#!/usr/bin/env python
from boofuzz import *


if __name__ == "__main__":
    fuzz_loggers = [FuzzLoggerCurses()]
    raise Exception()
```
Problems seem to occur when the exception happens in the script, prior to actually fuzzing. Just creating the FuzzLoggerCurses() object puts the console into the curses state. Perhaps we can hold off initialization until the fuzzing actually starts, or otherwise handle this corner case.

**Comment by SR4ven** [comment]
Thanks for the example @jtpereyda, I can reproduce it now.

I have a fix for the broken terminal using atexit, but that hides the exception. I'll see if I can find a solution for that.
