### ISSUE TITLE
error: pydbg: [50] DebugActiveProcess(2960): 不支持该请求。

### ISSUE THREAD

**Issue by highsky0** [jtpereyda/boofuzz#426]
![图片](https://user-images.githubusercontent.com/53111170/80161799-1e072f80-8604-11ea-851c-88a3e27c90b6.png)
Can anyone shed any light why this would be happening?

**Comment by jtpereyda** [comment]
Hi @highsky0 ! I don't know off hand -- do you have some context about the program you're running and the commands you're using?

**Comment by keisentraut** [comment]
The chinese error message is "The request is not supported". Maybe you wanted to debug a x64 application which is not possible with pydbg?

**Comment by SR4ven** [comment]
We no longer support debugging with pydbg, closing. Feel free to reopen.
