### ISSUE TITLE
Dependency crc32c requires compiler on Windows

### ISSUE THREAD

**Issue by SR4ven** [jtpereyda/boofuzz#436]
Installing boofuzz on Windows Python 3.8 failed for me because Microsoft Visual C++ Build Tools are required. This is caused by the dependency `crc32c`, which doesn't provide a wheel for Python 3.8 on Windows amd64 yet.

Maybe we should drop this dependency in favour of a simpler installation process?
I see three possibilities here:
- Completely remove crc32c form boofuzz and refer to the callback function which users can use to implement any checksum algorithm. crc32c was originally added in #353 because this feature was not properly documented, but it is now. https://boofuzz.readthedocs.io/en/latest/user/static-protocol-definition.html#boofuzz.s_checksum
- Remove the dependency, keep the implementation. This should work as we already have an include guard for crc32c. If the package is missing, the feature simply won't be available.
- Leave everything as it is and wait/hope for crc32c to release new wheels.

I don't know how many users are utilising the crc32c feature, so any input is welcome.

**Comment by jtpereyda** [comment]
Is that the only package on normal install requiring the compiler? Good find.

I was going to ask if you're interested in contributing a wheel build to the crc32c project 😄 , but on the downside it will just require new wheels with every Python release. Wait, are wheels not forward compatible? If they are maybe that can be a streamlined solution.

Of all your options, my first choice would be:
> Remove the dependency, keep the implementation. This should work as we already have an include guard for crc32c. If the package is missing, the feature simply won't be available.

Decent compromise between compatibility and making install easier.

Related thought: I wonder how hard it would be to make our own wheel build?

**Comment by SR4ven** [comment]
> Is that the only package on normal install requiring the compiler? Good find.
Yes it is.

With all extra requirements, `netifaces` also requires that compiler.

> I was going to ask if you're interested in contributing a wheel build to the crc32c project 😄 , but on the downside it will just require new wheels with every Python release. Wait, are wheels not forward compatible? If they are maybe that can be a streamlined solution.

If it was as easy as building the wheel and uploading it yes, but I'm not familiar with their CI workflow which appears to do that automatically.
Also, they don't appear to be forward compatible as there are wheels for amd64 cp37.

From the users perspective your choice is indeed rather convenient and a decent compromise. We'd also keep backward compatibility.
The downsides are that a warning message will be printed on every use of boofuzz warning about the missing package as well as a somewhat inconsistent code and dependency tree.
I'm not against that option, just wanted to share my thoughts but I'll leave the decision up to you.

Our release workflow already includes building a wheel for boofuzz. It's platform and architecture independent, so it's easy to create.
The only thing we're missing is a wheel for Python2, but as that is deprecated I didn't bother implementing it.

**Comment by jtpereyda** [comment]
That warning does seem obnoxious. What if we don't warn unless the algorithm is selected in an actual Checksum instance?

So if you install boofuzz via pip on Windows with Python 3.8, do you still need the compiler?

**Comment by SR4ven** [comment]
> That warning does seem obnoxious. What if we don't warn unless the algorithm is selected in an actual Checksum instance?

Yes, that's an option.

> So if you install boofuzz via pip on Windows with Python 3.8, do you still need the compiler?

As long as we have `crc32c` in our requirements and they don't provide a wheel, yes. Wheels are for one package only and don't include the dependencies if that's what you thought. At lease that's what I know.

**Comment by jtpereyda** [comment]
Well, if anything let's take it out and warn only if the algorithm is used.
