### ISSUE TITLE
duplicated data are found when using s_group with block

### ISSUE THREAD

**Issue by mengxiaolin** [jtpereyda/boofuzz#448]
When you tie a block with a group primitive,  let's say the following:
s_initialize("user")
    s_group("group1", values=[b"\x01", b"\x02",], default_value=b"\0x1")
    if s_block_start(name="block", group="group1"):
        s_byte([1,2])
        s_block_end()
what you are going to get is :
0101
0201

0101
0102
0201
0202
in total you get 6, and you should get 4, you can see there are duplicated data, that make no sense!

**Comment by jtpereyda** [comment]
Interesting! You might check out which element is being mutated during each case (the default console output will show this information). I suspect there is some subtlety with how block+group works, and/or with the default value behavior.
