### ISSUE TITLE
Fuzzing a client aborts with "Error!!!! Unexpected exception!"

### ISSUE THREAD

**Issue by hrantzsch** [jtpereyda/boofuzz#449]
I'm trying to fuzz a client by having boofuzz act as a server. For starters, I'm trying to run the [fuzz_ssl_client.py example](https://github.com/jtpereyda/boofuzz/blob/872d33be42e97b9e37bbe47a086aa585d8c50218/examples/fuzz_ssl_client.py).

Running the example opens the target connection and waits for a client to connect. However, connecting a client (for example `openssl s_client -connect 127.0.0.1`) crashes the server with
```
Error!!!! Unexpected exception! Traceback (most recent call last):
  [...]
  File [...]/boofuzz/connections/tcp_socket_connection.py", line 71, in open
    self._sock.connect((self.host, self.port))
OSError: [Errno 106] Transport endpoint is already connected
```

How can I make the server handle multiple connection attempts in order to continue fuzzing? I'm using boofuzz version 0.2.0 from pip.

**Comment by jtpereyda** [comment]
I haven't reproduced it yet but can try. What's your Python version and OS?

**Comment by SR4ven** [comment]
I was able to reproduce the error you've described.

Seems like a problem with the server implementation of `SSLSocketConnection`.

https://github.com/jtpereyda/boofuzz/blob/872d33be42e97b9e37bbe47a086aa585d8c50218/boofuzz/connections/ssl_socket_connection.py#L40
With this line we call `TCPSocketConnection.open()` which will connect to a client before calling `wrap_socket()`. So no wonder this isn't working.
The third example [here](https://docs.python.org/3/library/ssl.html#socket-creation) shows how it could be done.

At the moment I don't have much time, but when I find some time I'll see if I can fix this.
