### ISSUE TITLE
Issue using network monitor and probably callback monitor

### ISSUE THREAD

**Issue by Eki474** [jtpereyda/boofuzz#468]
### Summary

I tried to setup a network monitor to capture packets for each test case as described in the documentation. When setting up a network monitor, the first RPC command sent is not implemented in NetworkMonitor.

### Steps to reproduce

I used LightFTP server implementation to test but I believe any server would do.

* Activate python virtual environment
* Start FTP server
* Start network monitor server (network_monitor_server_example.py down below)
* Start fuzzing example (network_monitor_example.py down below)

### Expected results

* Fuzzing script connects to network monitor server
* Network monitor starts capturing packets for each test case

### Actual results

* Fuzzing script connects to network monitor server
* Fuzzing script sends `set_crash_filename` function call
* This function call is not implemented, the server crashes

### Findings

From what I understand every monitor implementation shall implements BaseMonitor to be a monitor. This interface does not force support for `set_crash_filename` function call and this function is only implemented in ProcessMonitor.

I found out that this option is systematically called by the session on every monitor regardless of their type ([here in code](https://github.com/jtpereyda/boofuzz/blob/master/boofuzz/sessions.py#L528)).

Is this function call necessary for all monitor types and shall be implemented in each one of them ? Or shall this function only be called on ProcessMonitor ?

I just started working on boofuzz, so maybe I misunderstood some behaviours in those findings. Thanks in advance for the help.

Regards,

### Network monitor server logs

```
ERR> USAGE: network_monitor.py
[-d|--device DEVICE #]    device to sniff on (see list below)
[-f|--filter PCAP FILTER] BPF filter string
[-P|--log_path PATH]      log directory to store pcaps to
[-l|--log_level LEVEL]    log level: default 1, increase for more verbosity
[--port PORT]             TCP port to bind this agent to
Network Device List:
[0] eth0    192.168.222.165
[1] any
[2] lo      127.0.0.1
[3] bond0
[4] dummy0
[5] sit0
[6] nflog
[7] nfqueue
[03:31.19] Network Monitor PED-RPC server initialized:
[03:31.19]       device:    None
[03:31.19]       filter:
[03:31.19]       log path:  ./
[03:31.19]       log_level: 1
[03:31.19] Awaiting requests...
PED-RPC> remote method "set_crash_filename" of <__main__.NetworkMonitorPedrpcServer object at 0x7fa6650c3940> cannot be found
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/home/ubuntu/boofuzz_testing/boofuzz/env/lib/python3.6/site-packages/boofuzz/monitors/pedrpc.py", line 343, in serve_forever
method = getattr(self, method_name)
AttributeError: 'NetworkMonitorPedrpcServer' object has no attribute 'set_crash_filename'
```

### Source files

Python files:

[network_monitor_example.py](https://github.com/jtpereyda/boofuzz/files/5305896/network_monitor_example.txt)
[network_monitor_server_example.py](https://github.com/jtpereyda/boofuzz/files/5305897/network_monitor_server_example.txt)

### Test environment

* Ubuntu 18.04
* Python3

Packages installed in python env:
* `pip install boofuzz`
* `pip install pcapy`
* `pip install netifaces`

**Comment by jtpereyda** [comment]
@mistressofjellyfish do you have any input on this one? Seems like our monitor changes broke compatibility with the network monitor.

**Comment by mistressofjellyfish** [comment]
Yeah, you're right. The problem once again stems from the... nice RPC protocol and was an oversight on my end. set_crash_filename is not relevant for the network monitor in particular, however the target doesn't really know what monitors it has, so it sets it for all regardless of the monitor type.

The root cause is the RPC interface not really equipped to handle arbitrary key/value option pairs. As a short-term fix I'd recommend just adding a stub of the function in question to network_monitor.py rpc script (not the boofuzz part but the script you load on the target host):

```python
def set_crash_filename(self):
    return
```

But really, the whole RPC interface has many more problems and is in need of a redesign for which I'm unfortunately lacking time.

**Comment by Eki474** [comment]
Hello again,

Thanks for your answer. I did find the same answer to the problem as you did. I worked on a fix on my own and can submit this "quick fix" as a pull request if you wish. I did not create a stub function but added a check for the monitor type before calling `set_crash_filename`.

I am not a python programmer, so maybe this solution is bad use of python. Nonetheless, it works fine (changes added in session.py line 528)

``` python
if type(monitor) == 'ProcessMonitor':
                    monitor.set_options(crash_filename=self._crash_filename)
```

With this change, I was able to partially use the network monitor and found another problem in the network monitor server example. The problem was mostly because of thread synchronization.

I will submit a pull request shortly with my changes if you wish to accept a quickfix while waiting for a RPC interface overhaul.

Regards,

**Comment by mistressofjellyfish** [comment]
If I have a say in this (@jtpereyda and @SR4ven are those who make the decision), I would not merge a fix that touches session.py, especially not in a way you did. When I re-designed the monitors it was a core principle that all monitors must adhere to the same API with no exceptions, so I'd much rather fix either the monitor RPC script or - even better - the whole monitor itself to use a better RPC protocol where this doesn't happen.

In any case, I'd happily look over the fixes related to thread synchronization.

**Comment by Eki474** [comment]
Ok I will submit my pull request with my fixes on the network monitor server and no quick fix.

**Comment by SR4ven** [comment]
With the two recent PRs merged everything mentioned here should be fixed now.
Thanks for the detailed report @Eki474
