### ISSUE TITLE
Changes in Boofuzz don't work

### ISSUE THREAD

**Issue by zhouzoe** [jtpereyda/boofuzz#475]
I just made some changes in boofuzz/primitives/word.py. However, this changes didn't seem to be woking!!!
Should I recompile boofuzz after I made changes ???
Here is changes I made in word.py
```
class Word(BitField):
    def __init__(self, value, *args, **kwargs):
        # Inject our width argument
        width = 16
        max_num = None
        super(Word, self).__init__(value, width, max_num, *args, **kwargs)

        ############ Here I added two lines that reset the value of self.max_num #############
        if self.name == "Error":        
        	self.max_num = 4095
        ############ ---------------------------------------------------------------- ##########333

        if not isinstance(self._value, (six.integer_types, list, tuple)):
            self._value = struct.unpack(self.endian + "H", self._value)[0]
```

**Comment by SR4ven** [comment]
Did you install boofuzz from source? If so you need to use the editable flag while installing: `pip install -e .[dev]`
See https://boofuzz.readthedocs.io/en/stable/user/install.html#from-source

**Comment by zhouzoe** [comment]
Thank you very much. I reinstalled boofuzz with option -e .[dev], and those changes I made works!!! @SR4ven
