### ISSUE TITLE
Convert pcap's into session code chunks

### ISSUE THREAD

**Issue by huornlmj** [jtpereyda/boofuzz#484]
It would be beneficial if there was a way to convert a packet capture into a session code chunk automatically.

**Comment by jtpereyda** [comment]
@huornlmj What do you mean by a "session code chunk"?

**Comment by huornlmj** [comment]
If there was a way to pass a pcap file in and have something like this auto generated:

```
s_initialize("lter")
s_static("LTER ")
s_string("A")
s_static("\r")
```

The above example is a very basic one used against the vulnserver.exe test program.  In this case it was very easy to generate the code chunk by hand as the command is a static 'LTER' command, followed by fuzzed material, then ending with a line return.  But it would take much longer to manually convert and translate a more complex structure into the Python code chunk needed.

**Comment by jtpereyda** [comment]
I think there are tools out there that try to parse or fuzz PCAPs. No such feature in boofuzz right now though.

**Comment by huornlmj** [comment]
Ok.  So just to confirm, the current best known method is to translate the network conversation into the code chunk manually?

**Comment by jtpereyda** [comment]
Yes. That's what I would do in this kind of situation.

As an aside, the simple example you gave already has more information than would be automatically obtainable by parsing the PCAP. You've chosen a certain element to be a string and others to be static.
