### ISSUE TITLE
Payload replay feature

### ISSUE THREAD

**Issue by huornlmj** [jtpereyda/boofuzz#495]
It would be useful if there was a built-in feature or tool that could replay a specific payload.  Currently the only method I know of is to manually take the payload out of the sqlite database and move it over to something like `nc`.  And curl and postman seem to damage the corpus and don't reliably send the payload without losing fidelity.

**Comment by SR4ven** [comment]
You could use [Session.fuzz_single_case(index)](https://boofuzz.readthedocs.io/en/stable/source/Session.html#boofuzz.Session.fuzz_single_case) to send the data for one specific test case.
But that only works if the test case data doesn't involve any random or dynamic data generation.

**Comment by jtpereyda** [comment]
Yes, the fuzz_single_case feature should work except for situations using random.

See #115 for an issue to get rid of the indeterminateness in boofuzz's usage of random.
