### ISSUE TITLE
Boofuzz a websocket client

### ISSUE THREAD

**Issue by juanrojascampos** [jtpereyda/boofuzz#498]
I want to fuzz a websockets client so i have to make a server with boofuzz. The problem is that we can make TCP/UDP/SSL connection but i do not know how to make a websocket connection

**Comment by SR4ven** [comment]
Websocket is an application layer protocol based on TCP just like HTTP right?
In that case you could configure boofuzz with a TCP server target connection just like you would with HTTP.
