### ISSUE TITLE
RawL3SocketConnection sends wrong data

### ISSUE THREAD

**Issue by jblu42** [jtpereyda/boofuzz#504]
Since I had problems with the checksum always fuzzing, I tried to update to boofuzz 0.3.0 (before I was on 0.2.1) but now my RawL3SocketConnection sends the wrong data. This is the script I use (shortend to replicate the error, this is no full packet)

```
from boofuzz import *

def main(): 
    interface = "eth0"
    l2destination = b'\xff\xff\xff\xff\xff\xff'

    session = Session(
        target=Target(
            connection=RawL3SocketConnection(interface, send_timeout=5.0, recv_timeout=5.0, ethernet_proto=2048,l2_dst=l2destination, packet_size=1500),
        ),
    )
     
    s_initialize(name="Request")
    s_static("\x4e\xfe\x01\x08\x00\x00\x40\x00") # Data
    s_byte(0x20, name='version')
    session.connect(s_get("Request"))

    session.fuzz()

if __name__ == "__main__":
    main()
```

And this is a wireshark hex dump of the frame I get:

0000   ff ff ff ff ff ff 00 0c 29 5b 87 83 08 00 4e c3
0010   be 01 08 00 00 40 00 0b 00 00 00 00 00 00 00 00
0020   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0030   00 00 00 00 00 00 00 00 00 00 00 00

There are the two mac addresses, followed by 08 00 for the IPv4 Protocol, then 4e as specified in the static above, but then followed by "c3 be" instead of "fe".

With boofuzz 0.2.1 this script works fine, but not with 0.3.0.

**Comment by SR4ven** [comment]
What happens here is that the string you pass to s_static gets encoded to bytes with the default encoding utf-8. That's why you're seeing different data in the hex dump.
Simply passing a bytes object to s_static should fix your problem.

```diff
    s_initialize(name="Request")
-   s_static("\x4e\xfe\x01\x08\x00\x00\x40\x00") # Data
+   s_static(b"\x4e\xfe\x01\x08\x00\x00\x40\x00") # Data
    s_byte(0x20, name='version')
    session.connect(s_get("Request"))
```
I hope that helps

**Comment by jblu42** [comment]
Thanks, this is working again.

I just wondered, if some of the examples should have had the same problem, but there was actually a commit to fix that, should have seen this earlier

Again, Thanks for your help.
