### ISSUE TITLE
s_bit_field smaller than 8 rounds to full byte

### ISSUE THREAD

**Issue by Martyx00** [jtpereyda/boofuzz#522]
I have noticed that using a block of:
```
s_initialize("ip_packet")
if s_block_start("ip_head"):
    s_bit_field(value=0x04, name="version", width=4, endian=">", fuzzable=False)
    s_bit_field(value=0x05, name="ihl", width=4, endian=">", fuzzable=False)
...
```

Results in the rounding of bit fields to bytes so that when the payload is sent I can observe:
`Transmitted 22 bytes: 04 05 00 00 00 `

Is there a way how to use `s_bit_field` with size smaller than 8 to connect two 4-bit values into one byte?

Thanks!

**Comment by shoeper** [comment]
https://github.com/jtpereyda/boofuzz/issues/88

**Comment by SR4ven** [comment]
Currently it's not possible to create primitives smaller than 8 bits. Thanks for reporting anyway.

Thanks for pointing out the duplicate @shoeper
