### ISSUE TITLE
s_static not static / integer issues

### ISSUE THREAD

**Issue by ploppelop** [jtpereyda/boofuzz#523]
Values over 0x7f get exploded, here \x80 is sent as \xc2\x80 breaking protocol conformance
```
from boofuzz import *
session = Session(
target=Target(connection=UDPSocketConnection("127.0.0.1", 1234)))
s_initialize("test")
s_byte(value=0x01)
# [2021-06-05 09:32:10,646]     Info: Sending 10 bytes...
# [2021-06-05 09:32:10,646]     Transmitted 10 bytes: ff 00 60 00 04 7f 5e c2 80 5b b'\xff\x00`\x00\x04\x7f^\xc2\x80['
s_static(name="mangled", value="\x00\x60\x00\x04\x7f\x5e\x80\x5b")
session.connect(s_get("test"))
session.fuzz()

```

**Comment by ploppelop** [comment]
traced it to https://github.com/jtpereyda/boofuzz/blob/29bab9d3ce054a211006d73bdacf1e8c412407ee/boofuzz/helpers.py#L444

**Comment by SR4ven** [comment]
Thanks for sharing your findings @ploppelop!

The issue here is that the string gets encoded to bytes, hence the differences.
Bytes `b""` is transmitted untouched, that's why it works. I think we've had a similar issue/question before.
Maybe we should add a note to the documentation.

**Comment by ploppelop** [comment]
sure, from using sulley back in the day i would expect s_static to be well, static :)
