### ISSUE TITLE
I want to start with the 0th testcase When I restart fuzzing.

### ISSUE THREAD

**Issue by tr4v3ler** [jtpereyda/boofuzz#536]
I found that every time I restart fuzzing, it will continue to execute the previous round of fuzzing. What can I do to make the execution start from the 0th testcase instead of the previous round of fuzzing when restarting fuzzing？

**Comment by cq674350529** [comment]
There is a `session_filename` option in `Session()`, which is used for that purpose. I'm not sure if you enable that. If yes, then just delete the corresponding session file.

**Comment by tr4v3ler** [comment]
> There is a `session_filename` option in `Session()`, which is used for that purpose. I'm not sure if you enable that. If yes, then just delete the corresponding session file.

Thank you. It really works!
