### ISSUE TITLE
Is it possible  to fuzz automotive ethernet protocol (AVB,DoIP,SoME/IP) in boofuzz?

### ISSUE THREAD

**Issue by Gokulllll** [jtpereyda/boofuzz#537]

**Comment by SR4ven** [comment]
Sure, should be possible if you have an ethernet device like eth0 in Linux that you can use to send packets to your targets.
In boofuzz you could use RawL2SocketConnection or RawL3SocketConnection to send ethernet or IP frames and write the protocol definitions for your desired protocols yourself.

**Comment by Gokulllll** [comment]
Thanks for your response @SR4ven
