### ISSUE TITLE
Docs: FuzzableBlock inheritance vs initialize children for Block

### ISSUE THREAD

**Issue by 678098** [jtpereyda/boofuzz#550]
Here guide says that for making your own primitive you should inherit from Fuzzable or FuzzableBlock:
https://github.com/jtpereyda/boofuzz/blob/373a5cb071f68b5076b098472db31de841c87389/docs/user/protocol-definition.rst#making-your-own-blockprimitive

Howewer, Request initialize children only for a Block primitive (which is inherited from FuzzableBlock).
https://github.com/jtpereyda/boofuzz/blob/373a5cb071f68b5076b098472db31de841c87389/boofuzz/blocks/request.py#L58

So basically if you just inherit from FuzzableBlock like instruction says, you will encounter uninitialized children for your custom block and there will be an exception when you try to fuzz. To get over this exception as a workaround you can just inherit from a Block primitive.

So how to fix it:
1. Update the check to initialize children for a FuzzableBlock.
2. Update instructions with advice to inherit from a Block.
3. Don't do anything. Then some people will probably encounter this problem when they will try to make a custom block according to instructions and they will have to look into inner implementation of Request building to find a similar workaround.

**Comment by SR4ven** [comment]
Thanks for reporting this inconsistency @678098.

I tend towards your first solution. Inheriting form `FuzzableBlock` seems to be the correct way as far as I can tell.

I'll open a PR.
