### ISSUE TITLE
TypeError: boofuzz.fuzzable.Fuzzable.__init__() got multiple values for keyword argument 'fuzzable'

### ISSUE THREAD

**Issue by kfr-ma** [jtpereyda/boofuzz#591]
### Report

Hi everybody ; 

When i try to run my boo fuzz program , i get this error : 

TypeError: boofuzz.fuzzable.Fuzzable.__init__() got multiple values for keyword argument 'fuzzable'

I am using Python 3.9.9 .

Below my test program : 

#!/usr/bin/env python

from boofuzz import *

def main():
    session = Session(
        target=Target(
            connection=SocketConnection("192.168.98.147", 69, proto='udp')),sleep_time = 3)

    s_initialize("Request")
    s_binary("0002")
    s_string("filename.txt", fuzzable=True)
    s_binary("00")
    s_string("netascii", fuzzable=True)
    s_binary("00")
    
    session.connect(s_get("Request"))
    session.fuzz()
   
if __name__ == "__main__":
    main()

Thx for your help.

### Expected behavior

start fuzzing 

### Actual behavior

[2022-01-04 11:10:12,344]     Info: Web interface can be found at http://localhost:26000
Traceback (most recent call last):
  File "/home/kali/src/boofuzz/examples/toto.py", line 21, in <module>
    main()
  File "/home/kali/src/boofuzz/examples/toto.py", line 11, in main
    s_binary("0002")
  File "/home/kali/.local/lib/python3.9/site-packages/boofuzz/__init__.py", line 596, in s_binary
    blocks.CURRENT.push(Static(name=name, default_value=parsed, fuzzable=False))
  File "/home/kali/.local/lib/python3.9/site-packages/boofuzz/primitives/static.py", line 16, in __init__
    super(Static, self).__init__(name=name, default_value=default_value, fuzzable=False, *args, **kwargs)
TypeError: boofuzz.fuzzable.Fuzzable.__init__() got multiple values for keyword argument 'fuzzable'

### Steps to reproduce the problem

1.
2.
3.

### boofuzz script

```python
#!/usr/bin/env python

from boofuzz import *

def main():
    session = Session(
        target=Target(
            connection=SocketConnection("192.168.98.147", 69, proto='udp')),sleep_time = 3)

    s_initialize("Request")
    s_binary("0002")
    s_string("filename.txt", fuzzable=True)
    s_binary("00")
    s_string("netascii", fuzzable=True)
    s_binary("00")
    
    session.connect(s_get("Request"))
    session.fuzz()
   
if __name__ == "__main__":
    main()
```

### boofuzz version

0.4.0

### Python version

3.9

### Platform

Linux

**Comment by SR4ven** [comment]
Thanks for your report @kfr-ma!

I've uploaded a potential fix in #592, could you test if these changes fix your problem please?
