### ISSUE TITLE
How can I run boofuzz with 0.0.0.0 host IP

### ISSUE THREAD

**Issue by zhouqianyi** [jtpereyda/boofuzz#617]
When I run boofuzz, the UI page can be accessed through  http://localhost:26000  or  http://127.0.0.1:26000,but not  http://local ip:26000. I think the IP monitored by port 26000 is 127.0.0.1 instead of 0.0.0.0, How can I run with 0.0.0.0 host IP.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/46179872/161783252-9ab4314b-1c56-4480-9983-884f11f24b7d.png">

**Comment by SR4ven** [comment]
Since #611 it is possible to chose any listening address for the webinterface.
This feature isn't in a released version yet, but you can install boofuzz from source. https://boofuzz.readthedocs.io/en/stable/user/install.html#from-source

**Comment by SR4ven** [comment]
Answered in #616
