### ISSUE TITLE
No boo utility

### ISSUE THREAD

**Issue by huornlmj** [jtpereyda/boofuzz#635]
### Report

Documentation says I can run
```console
boo open <run-*.db>
```
I install boofuzz in a virtual environment using pip3 install boofuzz.  When I try to run boo open <a-previous-sqlite-boofuzz-run.db> I get this:
```console
$ boo open run-2022-07-27T11-52-30.db

Command 'boo' not found, did you mean:

  command 'roo' from snap roo (2.0.3)
  command 'bovo' from snap bovo (21.12.1)
  command 'bovo' from deb bovo (4:19.12.3-0ubuntu1)
  command 'goo' from deb goo (0.155+ds-1)
  command 'boom' from deb doomsday (2.2.2+ds1-1)
  command 'boom' from deb prboom-plus (2:2.5.1.5+svn4540+dfsg1-1build1)
  command 'bos' from deb openafs-client (1.8.4~pre1-1ubuntu2.4)

See 'snap info <snapname>' for additional versions.

```

### Steps to reproduce the problem

1.
2.
3.

### boofuzz version

0.4.1

### Python version

3.8

### Platform

Linux

### Anything else?

Ubuntu 20.04

**Comment by huornlmj** [comment]
I found it.  It's in my virtual env dir/boofuzz/bin/, not part of my $PATH so I have to either add it manually or invoke it by full file path.

**Comment by SR4ven** [comment]
Thanks for sharing your solution @huornlmj!
