### ISSUE TITLE
Session.fuzz_by_name is deprecated in favor of Session.fuzz(name=name).

### ISSUE THREAD

**Issue by hackathi** [jtpereyda/boofuzz#640]
### Report

`Session.fuzz_by_name` unconditionally emits the following warning:

```
Session.fuzz_by_name is deprecated in favor of Session.fuzz(name=name).
```
 
However, if you look at the source code of Session.fuzz(name="something"), you'll find this:
https://github.com/jtpereyda/boofuzz/blob/5ee41f878b785d16c8bd9bbea8dd4f4c37525e1b/boofuzz/sessions.py#L1280-L1291

So the "correct" way to call this will trigger the warning.

### Expected behavior

No warning if the correct method is used.

### Actual behavior

Warning is displayed regardless of method used.

### Steps to reproduce the problem

1. use `session.fuzz(name="anything")`

### Anything else?

Proposed solution: move the code that is in `fuzz_by_name()` to `fuzz()`, let `fuzz_by_name()` call `fuzz(name=name)` instead.

**Comment by jtpereyda** [comment]
Thanks for the bug! The proposed solution makes sense to me.
